---
output: html_notebook
---
### Creating Data Visualizations - Demo

```{r}
# Load the ggplot2 library
library(ggplot2)
```

```{r}
# Read the CSV file
cars <- read.csv("Cars.csv")

head(cars)
```

<br>
**1. How many cars of each type of transmission?**

```{r}
# Create a frequency bar chart
ggplot(
    data = cars, 
    aes(x = Transmission)) + 
    geom_bar() +
    ggtitle("Count of Cars by Transmission Type") +
    xlab("Transmission Type") +
    ylab("Count of Cars")
```

<br>
**2. What does fuel economy look like? Miles per galon** <br>

```{r}
# Create a histogram
ggplot(
    data = cars, 
    aes(x = Fuel.Economy)) +
    geom_histogram(
        bins = 10) +
    ggtitle("Distribution of Fuel Economy") +
    xlab("Fuel Economy (mpg)") +
    ylab("Count of Cars")
```

```{r}
# Create a density plot
ggplot(
    data = cars, 
    aes(x = Fuel.Economy)) +
    geom_density() +
    ggtitle("Distribution of Fuel Economy") +
    xlab("Fuel Economy (mpg)") +
    ylab("Density")
```

**3. How are cylinders and fuel economy related?** <br>

```{r}

# Create a scatterplot
ggplot(
    data = cars, 
    aes(
        x = Cylinders,
        y = Fuel.Economy)) +
    geom_point() +
    ggtitle("Fuel Economy by Cylinders") +
    xlab("Number of Cylinders") +
    ylab("Fuel Economy (mpg)")
```
