---
output: html_notebook
---

### Handling Big Data - Demo

```{r}
library(ff)
# Load the biglm package
library(biglm)
```

```{r}
# Read a CSV file as ff data frame
irisff <- read.table.ffdf(
    file = "Iris.csv",
    FUN = "read.csv")
```

```{r}
# Inspect the class
class(irisff)
```

```{r}
# Inspect the column names
names(irisff)
```

```{r}
# Inspect the first few rows
irisff[1:5,]
```

```{r}
# Create a linear regression model
model <- biglm(
    formula = Petal.Width ~ Petal.Length,
    data = irisff)
summary(model)
```

```{r}
# Create a scatterplot
plot(
    x = irisff$Petal.Length[], 
    y = irisff$Petal.Width[],
    main = "Iris Petal Length vs. Width",
    xlab = "Petal Length (cm)",
    ylab = "Petal Width (cm)")
```

```{r}
# Get y-intercept from model
b <- summary(model)$mat[1,1]
# Get slope from model
m <- summary(model)$mat[2,1]
```

```{r}
# Draw a regression line on plot
plot(
    x = irisff$Petal.Length[], 
    y = irisff$Petal.Width[],
    main = "Iris Petal Length vs. Width",
    xlab = "Petal Length (cm)",
    ylab = "Petal Width (cm)")
lines(
    x = irisff$Petal.Length[],
    y = m * irisff$Petal.Length[] + b, 
    col = "red",
    lwd = 3)
```

```{r}
# Predict new values with the model
predict(
    object = model,
    newdata = data.frame(
        Petal.Length = c(2, 5, 7),
        Petal.Width = c(0, 0, 0)))
```
