---
output: html_notebook
---

### Predicting with Machine Learning - Demo

```{r}
# Load the data
data(iris)

# Set a seed to make randomness reproducible
set.seed(42)
# Randomly sample 100 of 150 row indexes
indexes <- sample(
    x = 1:150, 
    size = 100)

# Inspect the random indexes
print(indexes)
```


```{r}
# Create a training set from indexes
train <- iris[indexes, ]
```

```{r}
# Create a test set from remaining indexes
test <- iris[-indexes, ]
```

```{r}
# Load the decision tree package
library(tree)

```

```{r}
# Train a decision tree model
model <- tree(
    formula = Species ~ .,
    data = train)

summary(model)
```

```{r}
# Visualize the decision tree model
plot(model)
text(model)
```

```{r}
# Load color brewer library
library(RColorBrewer)
# Create a color palette
palette <- brewer.pal(3, "Set2")
# Create a scatterplot colored by species
plot(
    x = iris$Petal.Length, 
    y = iris$Petal.Width,
    pch = 19,
    col = palette[as.numeric(iris$Species)],
    main = "Iris Petal Length vs. Width",
    xlab = "Petal Length (cm)",
    ylab = "Petal Width (cm)")
```

```{r}
# Plot the decision boundaries
partition.tree(
    tree = model,
    label = "Species",
    add = TRUE)
```


```{r}
# Predict with the model
predictions <- predict(
    object = model,
    newdata = test,
    type = "class")

# Create a confusion matrix
table(
    x = predictions, 
    y = test$Species)
```

```{r}
# Load the caret package
library(caret)

# Evaluate the prediction results
confusionMatrix(
    data = predictions, 
    reference = test$Species)
```

```{r}
# Save the tree model
save(model, file = "Tree.RData")
# Save the training data
save(train, file = "Train.RData")

```
